### ISSUE TITLE
Default behavior of ::Pathname.parent() on Windows is changed

### ISSUE THREAD

**Issue by jakkn** [chef/win32-file#8]
Simply adding `require 'win32-file'` in a script that uses Pathname.parent() throws an error. If the working directory is one step further down then everything is fine.

OS: Win 10 x64
```
jakob /c/Users $ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
jakob /c/Users $ cat test.rb
```
```Ruby
require 'pathname'
require 'win32-file'

puts Pathname.pwd
puts Pathname.pwd.parent
```
```
jakob /c/users $ ruby test.rb
C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:44:in `[]': no implicit conversion from nil to integer (TypeError)
        from C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:44:in `chop_basename'
        from C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:370:in `plus'
        from C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:350:in `+'
        from C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:186:in `parent'
        from test.rb:5:in `<main>'
C:/users
jakob /c/Users $ cd jakob/
jakob ~ $ ruby ../test.rb
C:/Users/jakob
C:/Users
jakob ~ $
```

**Comment by jakkn** [comment]
@djberg96 issue that we discussed in the ptools project roughly 3 weeks ago. Any idea who I can ping to bring some attention to the issue?

**Comment by djberg96** [comment]
@btm Can you help @jakkn out?

**Comment by piyushawasthi** [comment]
Hi @djberg96, this issue fixed in PR: https://github.com/chef/win32-file/pull/9
